#define VIAL_UNLOCK_COMBO_ROWS {0, 0}
#define VIAL_UNLOCK_COMBO_COLS {1, 2}

#define OLED_IC OLED_IC_SSD1312
#define OLED_DISPLAY_128X64
#define OLED_FLIP_SEGMENT
#define OLED_DISPLAY_ADDRESS 0x3C
#define OLED_CHARGE_PUMP_VALUE 0x72
#define OLED_BRIGHTNESS 64
#define OLED_UPDATE_INTERVAL 60
#define OLED_TIMEOUT 0
#define OLED_TIMEOUT_USER 60000
#define OLED_FADE_OUT

#define SPLIT_TRANSPORT_MIRROR
#define SPLIT_WPM_ENABLE

#define SPLIT_TRANSACTION_IDS_USER USER_SYNC_ONTIME, USER_SYNC_LASTKEY, USER_SYNC_PRESSES
